{
 "title": "Aleo Validator",
 "tags": [ "aleo" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "DS_INFINITY",
    "query": "yesoreyeram-infinity-datasource"
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(snarkos_bft_height_total,job)"
    }
   },
   {
    "name": "chain",
    "query": {
     "query": "label_values(snarkos_bft_height_total{job=\"$job\"},chain)"
    }
   },
   {
    "name": "api",
    "query": "https://canarynet-aleo-api.lavenderfive.com:443/mainnet"
   }
  ]
 },
 "panels": [
  { "title": "Aleo", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Block Height",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(snarkos_bft_height_total{chain=\"$chain\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proposal Round",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "snarkos_bft_primary_proposal_round{role=\"validator\",chain=\"$chain\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Coinbase Target",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "snarkos_blocks_coinbase_target{role=\"validator\",chain=\"$chain\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proof Target",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "snarkos_blocks_proof_target{role=\"validator\",chain=\"$chain\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Committed Certificates",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "snarkos_consensus_committed_certificates_total{role=\"validator\",chain=\"$chain\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Elected Leaders",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "snarkos_bft_leaders_elected_total{role=\"validator\",chain=\"$chain\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Stake",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "snarkvm_ledger_committee_total_stake{role=\"validator\",chain=\"$chain\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Solutions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(snarkos_blocks_solutions_total{chain=\"$chain\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(snarkos_blocks_transactions_total{chain=\"$chain\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Node Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Validator Height Increasing?",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(snarkos_bft_height_total{role=\"validator\",chain=\"$chain\"}[5m]) > bool 1"
    }
   ]
  },
  {
   "title": "Validator Active?",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{chain=\"$chain\", role=\"validator\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validator Bonded?",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "snarkos_consensus_committed_certificates_total{chain=\"$chain\", role=\"validator\"} > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validator Block Height",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "snarkos_bft_height_total{role=\"validator\",chain=\"$chain\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Client Height Increasing?",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(snarkos_bft_height_total{role=\"client\",chain=\"$chain\"}[5m]) > bool 1"
    }
   ]
  },
  {
   "title": "Client Active?",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{chain=\"$chain\", role=\"client\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Client Block Heights",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 6, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "snarkos_bft_height_total{role=\"client\",chain=\"$chain\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Chain Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Block Speed (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "1 / avg(rate(snarkos_bft_height_total{chain=\"$chain\"}[15m]))",
     "legendFormat": "Block Time - 15min average"
    },
    {
     "expr": "1 / avg(rate(snarkos_bft_height_total{chain=\"$chain\"}[6h]))",
     "legendFormat": "Block Time - 6h average"
    },
    {
     "expr": "1 / avg(rate(snarkos_bft_height_total{chain=\"$chain\"}[1d])) ",
     "legendFormat": "Block Time - 24h average"
    },
    {
     "expr": "1 / avg(increase(snarkos_bft_height_total{chain=\"$chain\"}[45s]))",
     "legendFormat": "Blocks Produced"
    }
   ]
  },
  {
   "title": "Proposal Rounds (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "1 / avg(rate(snarkos_bft_primary_proposal_round{chain=\"$chain\"}[15m]))",
     "legendFormat": "Proposal Round - 15min average"
    },
    {
     "expr": "1 / avg(rate(snarkos_bft_primary_proposal_round{chain=\"$chain\"}[6h]))",
     "legendFormat": "Proposal Round - 6h average"
    },
    {
     "expr": "1 / avg(rate(snarkos_bft_primary_proposal_round{chain=\"$chain\"}[1d])) ",
     "legendFormat": "Proposal Round - 24h average"
    },
    {
     "expr": "1 / avg(increase(snarkos_bft_primary_proposal_round{chain=\"$chain\"}[45s]))",
     "legendFormat": "Proposals Produced"
    }
   ]
  },
  {
   "title": "6h Txs Overview / min",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(rate(snarkos_blocks_transactions_total{role=\"validator\",chain=\"$chain\"}[6h])) * 60",
     "legendFormat": "Successful Tx / min"
    },
    {
     "expr": "avg(rate(snarkos_consensus_unconfirmed_transactions_total{role=\"validator\",chain=\"$chain\"}[6h])) * 60",
     "legendFormat": "Failed Tx / min"
    },
    {
     "expr": "avg(rate(snarkos_blocks_aborted_transactions{role=\"validator\",chain=\"$chain\"}[6h])) * 60",
     "legendFormat": "Aborted Tx / min"
    }
   ]
  },
  {
   "title": "6h Block Solution Overview / min",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(rate(snarkos_blocks_solutions_total{role=\"validator\",chain=\"$chain\"}[6h])) * 60",
     "legendFormat": "Block Solutions / min"
    },
    {
     "expr": "avg(rate(snarkos_consensus_unconfirmed_solutions_total{role=\"validator\",chain=\"$chain\"}[6h])) * 60",
     "legendFormat": "Failed Solutions / min"
    },
    {
     "expr": "avg(rate(snarkos_blocks_aborted_solutions{role=\"validator\",chain=\"$chain\"}[6h])) * 60",
     "legendFormat": "Aborted Solutions / min"
    }
   ]
  },
  {
   "title": "Restricted Peers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "snarkos_router_restricted_total{chain=\"$chain\"}",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 16, "x": 8, "y": 39 },
   "targets": [
    {
     "expr": "snarkos_router_connected_total{chain=\"$chain\"}",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "TCP Queue Depth",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "snarkos_tcp_tasks_total{chain=\"$chain\"}",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "Total Clients",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "snarkos_router_candidate_total{chain=\"$chain\"}",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "Consensus",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "collapsed": true,
   "panels": [
    {
     "title": "Certificate Commit Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(snarkos_consensus_certificate_commit_latency_secs{chain=\"$chain\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Commit Rounds Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 8, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(snarkos_bft_commit_rounds_latency_secs{chain=\"$chain\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Block Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(snarkos_consensus_block_latency_secs{chain=\"$chain\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}