{
 "title": "CloudFlare Zone Analytics",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "zone",
    "query": {
     "query": "label_values(cloudflare_zone_requests_total, zone)"
    }
   },
   {
    "name": "regions",
    "query": {
     "query": "label_values(cloudflare_zone_requests_country, region)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cloudflare_zone_requests_total{zone=\"$zone\"}"
    }
   ]
  },
  {
   "title": "Total Bandwidth",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "increase(cloudflare_zone_bandwidth_total{zone=~\"$zone\"}[$__range])"
    }
   ]
  },
  {
   "title": "Requests / second",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(cloudflare_zone_requests_total{zone=~\"$zone\"}[$__interval])"
    }
   ]
  },
  {
   "title": "Bandwidth / second",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(cloudflare_zone_bandwidth_total{zone=~\"$zone\"}[$__interval])"
    }
   ]
  },
  {
   "title": "Total Unique Visitors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "increase(cloudflare_zone_uniques_total{zone=~\"$zone\"}[$__range])"
    }
   ]
  },
  {
   "title": "Uniques / second",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(cloudflare_zone_uniques_total{zone=~\"$zone\"}[$__interval])"
    }
   ]
  },
  {
   "title": "Unique Visitors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cloudflare_zone_uniques_total{zone=~\"$zone\"}[$__interval])",
     "legendFormat": "visitors"
    }
   ]
  },
  {
   "title": "Requests in North America / second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cloudflare_zone_requests_country{zone=~\"$zone\", region=\"North America\"}[$__interval]) > 10",
     "legendFormat": "{{ country }}"
    }
   ]
  },
  {
   "title": "Requests in Europe / second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cloudflare_zone_requests_country{zone=~\"$zone\", region=\"Europe\"}[$__interval]) > 10",
     "legendFormat": "{{ country }}"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Requests / second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cloudflare_zone_requests_total{zone=~\"$zone\"}[$__interval])",
     "legendFormat": "total"
    },
    {
     "expr": "rate(cloudflare_zone_requests_cached{zone=~\"$zone\"}[$__interval])",
     "legendFormat": "cached"
    }
   ]
  },
  {
   "title": "Requests per Country / Second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cloudflare_zone_requests_country{zone=~\"$zone\"}[$__interval]) > 0",
     "legendFormat": "{{country}}"
    }
   ]
  },
  {
   "title": "Requests / Second (status codes)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cloudflare_zone_requests_status{zone=~\"$zone\", status!~\"5..\"}[$__interval]) ",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Requests / Second (status codes not 2XX)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(cloudflare_zone_requests_status{zone=~\"$zone\", status!~\"2..\"}[$__interval]) ",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Cached Requests",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cloudflare_zone_requests_cached{zone=~\"$zone\"} / cloudflare_zone_requests_total{zone=~\"$zone\"}",
     "legendFormat": "cached"
    },
    {
     "expr": "(cloudflare_zone_requests_total{zone=~\"$zone\"} - cloudflare_zone_requests_cached{zone=~\"$zone\"}) / cloudflare_zone_requests_total{zone=~\"$zone\"}",
     "legendFormat": "uncached"
    }
   ]
  },
  {
   "title": "Requests SSL",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cloudflare_zone_requests_ssl_encrypted{zone=~\"$zone\"} / cloudflare_zone_requests_total{zone=~\"$zone\"}",
     "legendFormat": "encrypted"
    },
    {
     "expr": "( cloudflare_zone_requests_total{zone=~\"$zone\"} - cloudflare_zone_requests_ssl_encrypted{zone=~\"$zone\"}  ) / cloudflare_zone_requests_total{zone=~\"$zone\"}",
     "legendFormat": "unencrypted"
    }
   ]
  },
  {
   "title": "Errors / Second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cloudflare_zone_requests_status{zone=~\"$zone\", status=~\"5..\"}[$__interval]) ",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Request Country",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(cloudflare_zone_requests_country{zone=~\"$zone\"}[$__range])",
     "legendFormat": "{{country}}"
    }
   ]
  },
  {
   "title": "Request Content Type",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(cloudflare_zone_requests_content_type{zone=~\"$zone\"}[$__range])",
     "legendFormat": "{{content_type}}"
    }
   ]
  },
  {
   "title": "Requests Status Codes",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(cloudflare_zone_requests_status{zone=~\"$zone\"}[$__range])",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Bandwidth / second",
   "type": "graph",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(cloudflare_zone_bandwidth_total{zone=~\"$zone\"}[$__interval])",
     "legendFormat": "total"
    },
    {
     "expr": "rate(cloudflare_zone_bandwidth_cached{zone=~\"$zone\"}[$__interval])",
     "legendFormat": "cached"
    }
   ]
  },
  {
   "title": "Cached Bandwidth",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 81 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cloudflare_zone_bandwidth_cached{zone=~\"$zone\"} / cloudflare_zone_bandwidth_total{zone=~\"$zone\"}",
     "legendFormat": "cached"
    },
    {
     "expr": "(cloudflare_zone_bandwidth_total{zone=~\"$zone\"} - cloudflare_zone_bandwidth_cached{zone=~\"$zone\"}) / cloudflare_zone_bandwidth_total{zone=~\"$zone\"}",
     "legendFormat": "uncached"
    }
   ]
  },
  {
   "title": "Bandwidth Content Type",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 11, "x": 12, "y": 81 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(cloudflare_zone_bandwidth_content_type{zone=~\"$zone\"}[5m])",
     "legendFormat": "{{content_type}}"
    }
   ]
  },
  {
   "title": "Regions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Requests by Region / second",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 92 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (region)(rate(cloudflare_zone_requests_country{zone=~\"$zone\"}[$__interval]))",
     "legendFormat": "{{ region }}"
    }
   ]
  },
  {
   "title": "Bandwidth by Region / second",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 92 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (region)(rate(cloudflare_zone_bandwidth_country{zone=~\"$zone\"}[$__interval]))",
     "legendFormat": "{{ region }}"
    }
   ]
  },
  {
   "title": "Requests in $regions / second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 102 },
   "repeat": "regions",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cloudflare_zone_requests_country{zone=~\"$zone\", region=~\"$regions\"}[$__interval]) > 10",
     "legendFormat": "{{ country }}"
    }
   ]
  },
  {
   "title": "Threats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 109 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Threats / second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 110 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cloudflare_zone_threats_total{zone=~\"$zone\"}[1m])",
     "legendFormat": "{{zone}}/threats"
    }
   ]
  },
  {
   "title": "Threats / country",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 110 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cloudflare_zone_threats_country{zone=~\"$zone\"}[1m])",
     "legendFormat": "{{country}}/threats"
    }
   ]
  },
  {
   "title": "Threats / type",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 118 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cloudflare_zone_threats_type{zone=~\"$zone\"}[1m])",
     "legendFormat": "{{type}}/threats"
    }
   ]
  },
  {
   "title": "Colocations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 126 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Visits  by Colocations / second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 127 },
   "repeat": "zone",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cloudflare_zone_colocation_visits{zone=\"$zone\"}[$__interval]) > 0",
     "legendFormat": "{{ colocation }}"
    }
   ]
  }
 ]
}