{
 "title": "Cosmos Oracles and Orchestrators",
 "description": "Orchestrators, Oracles, etc.,",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "General Up Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Carbon Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"65.108.238.103:19628\",job=\"carbon@oracle\"}"
    }
   ]
  },
  {
   "title": "Sei Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"57.128.96.155:7171\",job=\"sei-price-feeder\"}"
    }
   ]
  },
  {
   "title": "Kujira Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"kujira-price-feeder\"}"
    }
   ]
  },
  {
   "title": "Nomic Signer Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"nomic-signer\"}"
    }
   ]
  },
  {
   "title": "GBT Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"gbt\", instance=\"142.132.158.93:6631\"}"
    }
   ]
  },
  {
   "title": "Steward Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"steward\"}"
    }
   ]
  },
  {
   "title": "Yoda Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"yoda\"}"
    }
   ]
  },
  {
   "title": "Carbon Oracle",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Vote Status",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "up{instance=\"65.108.238.103:19628\",job=\"carbon@oracle\"}",
       "legendFormat": "Vote Status"
      }
     ]
    }
   ]
  },
  { "title": "Gravity Bridge GBT", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Risking Slashing Warnings",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "orchestrator_errors_count_cosmos{error_message=\"Failed to get Gravity parameters correct your Cosmos gRPC connection immediately, you are risking slashing\"}"
    }
   ]
  },
  {
   "title": "Gravity Bridge Height",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "orchestrator_information{chain=\"gravity-bridge-3\", gauge=\"latest_cosmos_block\", instance=\"142.132.158.93:6631\", job=\"gbt\"}"
    }
   ]
  },
  {
   "title": "Ethereum Height",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "orchestrator_information{chain=\"gravity-bridge-3\", gauge=\"latest_eth_block\", instance=\"142.132.158.93:6631\", job=\"gbt\"}"
    }
   ]
  },
  {
   "title": "L5 Last Event",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "orchestrator_information{gauge=\"last_checked_event\", instance=\"142.132.158.93:6631\"}"
    }
   ]
  },
  {
   "title": "L5 Gravity Connection",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(orchestrator_warnings_count_cosmos{job=\"gbt\", warn_message=\"Could not contact Cosmos grpc\"}[1h])*3600"
    }
   ]
  },
  {
   "title": "Rhino ETH Connection",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(orchestrator_warnings_count_eth{warn_message=\"Could not contact Eth node\"}[1h])*3600"
    }
   ]
  },
  {
   "title": "Errors Count (1h Avg)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "rate(orchestrator_errors_count_total{job=\"gbt\", instance=\"142.132.158.93:6631\"}[1h])*3600",
     "legendFormat": "Total Errors"
    },
    {
     "expr": "rate(orchestrator_errors_count_cosmos_eth{job=\"gbt\"}[1h])*3600",
     "legendFormat": "Cosmos ETH"
    }
   ]
  },
  {
   "title": "Warnings Count (1h Avg)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "rate(orchestrator_warnings_count_cosmos{job=\"gbt\",warn_message=\"Cosmos node syncing\", instance=\"142.132.158.93:6631\"}[1h])*3600",
     "legendFormat": "Cosmos node syncing"
    },
    {
     "expr": "rate(orchestrator_warnings_count_cosmos{job=\"gbt\", warn_message=\"Cosmos node syncing, Eth signer paused\"}[1h])*3600",
     "legendFormat": "Eth Signer Paused"
    },
    {
     "expr": "rate(orchestrator_warnings_count_cosmos{job=\"gbt\", warn_message=\"Could not contact Cosmos grpc\"}[1h])*3600",
     "legendFormat": "Could not contact Cosmos gRPC"
    }
   ]
  },
  { "title": "Injective Peggo", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Last Claim Event",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "columns": [
      { "selector": "ethereum_event_nonce", "text": "", "type": "string" }
     ],
     "groq": "*",
     "parser": "backend",
     "root_selector": "last_claim_event",
     "source": "url",
     "type": "json",
     "uql": "parse-json",
     "url": "https://injective-api.lavenderfive.com/peggy/v1/oracle/event/inj1ztzjaptslmd7qxz4x8zjv747jrn5gqgfvfy6md",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "L5 API Nonce",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "columns": [
      { "selector": "last_observed_nonce", "text": "", "type": "string" }
     ],
     "groq": "*",
     "parser": "backend",
     "root_selector": "state",
     "source": "url",
     "type": "json",
     "uql": "parse-json",
     "url": "https://injective-api.lavenderfive.com/peggy/v1/module_state",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Ethereum Height",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "columns": [
      { "selector": "last_observed_ethereum_height", "text": "", "type": "string" }
     ],
     "groq": "*",
     "parser": "backend",
     "root_selector": "state",
     "source": "url",
     "type": "json",
     "uql": "parse-json",
     "url": "https://injective-api.lavenderfive.com/peggy/v1/module_state",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Injective API Nonce",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "columns": [
      { "selector": "last_observed_nonce", "text": "", "type": "string" }
     ],
     "groq": "*",
     "parser": "backend",
     "root_selector": "state",
     "source": "url",
     "type": "json",
     "uql": "parse-json",
     "url": "https://lcd.injective.network/peggy/v1/module_state",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Master 10 Nonce",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "columns": [
      { "selector": "last_observed_nonce", "text": "", "type": "string" }
     ],
     "groq": "*",
     "parser": "backend",
     "root_selector": "state",
     "source": "url",
     "type": "json",
     "uql": "parse-json",
     "url": "http://51.210.223.72:10337/peggy/v1/module_state",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Pending Batches",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "columns": [
      { "selector": "", "text": "", "type": "string" }
     ],
     "groq": "*",
     "parser": "backend",
     "root_selector": "batch",
     "source": "url",
     "type": "json",
     "uql": "parse-json",
     "url": "https://lcd.injective.network/peggy/v1/batch/last?address=inj1ztzjaptslmd7qxz4x8zjv747jrn5gqgfvfy6md",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Peggo Nonce",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "targets": [
    { "expr": "peggo_network_nonce", "legendFormat": "Network Nonce" },
    { "expr": "peggo_orchestrator_nonce", "legendFormat": "Peggo Nonce" }
   ]
  },
  { "title": "Kujira Price Feeder", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Miss Counter",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "columns": [
      { "selector": "miss_counter", "text": "", "type": "string" }
     ],
     "groq": "*",
     "json_options": {
      "columnar": false,
      "root_is_not_array": false
     },
     "parser": "backend",
     "source": "url",
     "type": "json",
     "uql": "parse-json",
     "url": "https://kujira-api.lavenderfive.com/oracle/validators/kujiravaloper140l6y2gp3gxvay6qtn70re7z2s0gn57z6yz0hy/miss",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Feeder Address",
   "type": "table",
   "gridPos": { "h": 3, "w": 8, "x": 7, "y": 41 },
   "targets": [
    {
     "groq": "*",
     "json_options": {
      "columnar": true
     },
     "parser": "backend",
     "source": "url",
     "type": "json",
     "uql": "parse-json",
     "url": "https://kujira-api.lavenderfive.com/oracle/validators/kujiravaloper140l6y2gp3gxvay6qtn70re7z2s0gn57z6yz0hy/feeder",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Active Denoms",
   "type": "table",
   "gridPos": { "h": 11, "w": 4, "x": 0, "y": 44 },
   "targets": [
    {
     "json_options": {
      "columnar": true,
      "root_is_not_array": false
     },
     "source": "url",
     "type": "json",
     "url": "https://kujira-api.lavenderfive.com/oracle/denoms/actives",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Provider Failure/Timeout, Vote Miss",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 20, "x": 4, "y": 44 },
   "targets": [
    {
     "expr": "price_feeder_failure_provider_type_timeout{job=\"kujira-price-feeder\"}",
     "legendFormat": "Provider Timeout"
    },
    {
     "expr": "price_feeder_failure_tx_timeout{job=\"kujira-price-feeder\"}",
     "legendFormat": "TX Timeout"
    },
    {
     "expr": "price_feeder_vote_failure_missed{job=\"kujira-price-feeder\"}",
     "legendFormat": "Vote Miss"
    }
   ]
  },
  {
   "title": "Tick",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "price_feeder_new_tick{job=\"kujira-price-feeder\"}",
     "legendFormat": "New Tick"
    },
    {
     "expr": "price_feeder_failure_tick{job=\"kujira-price-feeder\"}",
     "legendFormat": "Fail"
    }
   ]
  },
  { "title": "Nomic Signer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Checkpoint Index",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "nomic_signer_checkpoint_index{job=\"nomic-signer\"}",
     "legendFormat": "Checkpoint Index"
    }
   ]
  },
  {
   "title": "Checkpoint Timestamp",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "targets": [
    {
     "expr": "nomic_signer_checkpoint_timestamp{job=\"nomic-signer\"}",
     "legendFormat": "Checkpoint Timestamp"
    }
   ]
  },
  {
   "title": "Sigset Change Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "targets": [
    {
     "expr": "nomic_signer_sigset_change_rate{job=\"nomic-signer\"}",
     "legendFormat": "Sigset Change Rate"
    }
   ]
  },
  {
   "title": "Withdrawal Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "targets": [
    {
     "expr": "nomic_signer_withdrawal_rate{job=\"nomic-signer\"}",
     "legendFormat": "Withdrawal Rate"
    }
   ]
  },
  { "title": "Sei Price Feeder", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "title": "Oracle Price Update",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 84 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "sei_oracle_price_update{chain=\"pacific-1\", denom=\"ubtc\", instance=\"136.243.67.47:11961\", job=\"sei\"}",
     "legendFormat": "uBTC"
    },
    {
     "expr": "sei_oracle_price_update{chain=\"pacific-1\", denom=\"ueth\", instance=\"136.243.67.47:11961\", job=\"sei\"}",
     "legendFormat": "uETH"
    },
    {
     "expr": "sei_oracle_price_update{chain=\"pacific-1\", denom=\"uusdc\", instance=\"136.243.67.47:11961\", job=\"sei\"}",
     "legendFormat": "uUSDC"
    },
    {
     "expr": "sei_oracle_price_update{chain=\"pacific-1\", denom=\"uusdt\", instance=\"136.243.67.47:11961\", job=\"sei\"}",
     "legendFormat": "uUSDT"
    },
    {
     "expr": "sei_oracle_price_update{chain=\"pacific-1\", denom=\"uosmo\", instance=\"136.243.67.47:11961\", job=\"sei\"}",
     "legendFormat": "uOSMO"
    },
    {
     "expr": "sei_oracle_price_update{chain=\"pacific-1\", denom=\"uatom\", instance=\"136.243.67.45:11961\", job=\"sei\"}",
     "legendFormat": "uATOM"
    },
    {
     "expr": "sei_oracle_price_update{chain=\"pacific-1\", denom=\"usei\", instance=\"136.243.67.47:11961\", job=\"sei\"}",
     "legendFormat": "uSEI"
    }
   ]
  },
  {
   "title": "L5 Oracle Performance",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 84 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sei_oracle_vote_penalty_count{chain=\"pacific-1\", instance=\"136.243.67.47:11961\", job=\"sei\", type=\"abstain\", validator=\"seivaloper140l6y2gp3gxvay6qtn70re7z2s0gn57zl6nups\"}",
     "legendFormat": "Abstain"
    },
    {
     "expr": "sei_oracle_vote_penalty_count{chain=\"pacific-1\", instance=\"136.243.67.47:11961\", job=\"sei\", type=\"miss\", validator=\"seivaloper140l6y2gp3gxvay6qtn70re7z2s0gn57zl6nups\"}",
     "legendFormat": "Miss"
    },
    {
     "expr": "sei_oracle_vote_penalty_count{chain=\"pacific-1\", instance=\"136.243.67.47:11961\", job=\"sei\", type=\"success\", validator=\"seivaloper140l6y2gp3gxvay6qtn70re7z2s0gn57zl6nups\"}",
     "legendFormat": "Success"
    }
   ]
  },
  {
   "title": "Oracle Performance Graph",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 91 },
   "targets": [
    {
     "expr": "sei_oracle_vote_penalty_count{chain=\"pacific-1\", instance=\"136.243.67.47:11961\", job=\"sei\", type=\"abstain\", validator=\"seivaloper140l6y2gp3gxvay6qtn70re7z2s0gn57zl6nups\"}",
     "legendFormat": "Abstain"
    },
    {
     "expr": "sei_oracle_vote_penalty_count{chain=\"pacific-1\", instance=\"136.243.67.47:11961\", job=\"sei\", type=\"success\", validator=\"seivaloper140l6y2gp3gxvay6qtn70re7z2s0gn57zl6nups\"}",
     "legendFormat": "Success"
    },
    {
     "expr": "sei_oracle_vote_penalty_count{chain=\"pacific-1\", instance=\"136.243.67.47:11961\", job=\"sei\", type=\"miss\", validator=\"seivaloper140l6y2gp3gxvay6qtn70re7z2s0gn57zl6nups\"}",
     "legendFormat": "Miss"
    }
   ]
  },
  {
   "title": "Broadcast Failures",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 99 },
   "targets": [
    {
     "expr": "price_feeder_failure_broadcast{instance=\"57.128.96.155:7171\",job=\"sei-price-feeder\"}",
     "legendFormat": "Broadcast Failures"
    }
   ]
  },
  {
   "title": "Skipped Blocks",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 99 },
   "targets": [
    {
     "expr": "price_feeder_skipped_blocks_tick{instance=\"57.128.96.155:7171\",job=\"sei-price-feeder\"}",
     "legendFormat": "Skipped Blocks"
    }
   ]
  },
  {
   "title": "Provider Candle Fail",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 108 },
   "targets": [
    {
     "expr": "price_feeder_failure_provider_type_candle{instance=\"57.128.96.155:7171\",job=\"sei-price-feeder\"}",
     "legendFormat": "Provider Timeout"
    }
   ]
  },
  {
   "title": "Ticker",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 108 },
   "targets": [
    {
     "expr": "price_feeder_success_tick{instance=\"57.128.96.155:7171\",job=\"sei-price-feeder\"}",
     "legendFormat": "Success"
    },
    {
     "expr": "price_feeder_failure_tick{instance=\"57.128.96.155:7171\",job=\"sei-price-feeder\"}",
     "legendFormat": "Fail"
    }
   ]
  },
  {
   "title": "Sommelier Steward",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 117 },
   "collapsed": true,
   "panels": [
    {
     "title": "L5 Somm Connection",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 28 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(cosmos_unavailable{job=\"steward\"}[1h])*3600",
       "legendFormat": "Cosmos Unavailable"
      }
     ]
    },
    {
     "title": "Rhino Eth Connection",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 28 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "rate(ethereum_event_check_failures{job=\"steward\"}[1h])*3600",
       "legendFormat": "Cosmos Unavailable"
      }
     ]
    },
    {
     "title": "L5 Cosmos Nonce",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 28 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cosmos_last_event_nonce{job=\"steward\"}"
      }
     ]
    },
    {
     "title": "Sommelier Height",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cosmos_block_height{job=\"steward\"}"
      }
     ]
    },
    {
     "title": "Ethereum Height",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ethereum_last_deposit_block{job=\"steward\"}"
      }
     ]
    },
    {
     "title": "Cosmos / Ethereum Unavailable (1h Avg)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 31 },
     "targets": [
      {
       "expr": "rate(cosmos_unavailable{job=\"steward\"}[1h])*3600",
       "legendFormat": "Cosmos Unavailable"
      },
      {
       "expr": "rate(ethereum_unavailable{job=\"steward\"}[1h])*3600",
       "legendFormat": "Ethereum Unavailble"
      }
     ]
    },
    {
     "title": "Failures (1h Avg)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 31 },
     "targets": [
      {
       "expr": "rate(unsigned_batch_failures{job=\"steward\"}[1h])*3600",
       "legendFormat": "Batch Failures"
      },
      {
       "expr": "rate(unsigned_logic_call_failures{job=\"steward\"}[1h])*3600",
       "legendFormat": "Logic Call Failures"
      },
      {
       "expr": "rate(unsigned_valset_failures{job=\"steward\"}[1h])*3600",
       "legendFormat": "Valset Failures"
      },
      {
       "expr": "rate(ethereum_event_check_failures{job=\"steward\"}[1h])*3600",
       "legendFormat": "Event Check Fails"
      }
     ]
    }
   ]
  },
  {
   "title": "Yoda",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 118 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "targets": [
      {
       "expr": "yoda_reports_error_total{job=\"yoda\"}",
       "legendFormat": "Total Errors"
      }
     ]
    },
    {
     "title": "Reports",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "targets": [
      {
       "expr": "yoda_reports_handling_count{job=\"yoda\"}",
       "legendFormat": "Handling Count"
      },
      {
       "expr": "yoda_reports_pending_count{job=\"yoda\"}",
       "legendFormat": "Pending Count"
      },
      {
       "expr": "yoda_reports_submitted_total{job=\"yoda\"}",
       "legendFormat": "Total Reports"
      }
     ]
    }
   ]
  }
 ]
}