{
 "title": "Peggo Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "orchestrator_address",
    "query": {
     "query": "label_values(peggo_network_nonce, orchestrator_address)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Peggo Signing?",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "abs(peggo_network_nonce - peggo_orchestrator_nonce)",
     "legendFormat": "__auto"
    },
    {
     "expr": "increase(peggo_orchestrator_nonce[15m]) >= 0"
    },
    {
     "conditions": [
      {
       "evaluator": {
        "params": [
         5,
         0
        ],
        "type": "gt"
       },
       "operator": { "type": "and" },
       "query": { "params": [ "A" ] },
       "reducer": {
        "params": [],
        "type": "avg"
       },
       "type": "query"
      },
      {
       "evaluator": {
        "params": [
         1,
         0
        ],
        "type": "lt"
       },
       "operator": { "type": "or" },
       "query": { "params": [ "B" ] },
       "reducer": {
        "params": [],
        "type": "avg"
       },
       "type": "query"
      }
     ],
     "type": "classic_conditions"
    }
   ]
  },
  {
   "title": "Nonce Lag",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "peggo_network_nonce", "legendFormat": "__auto" },
    { "expr": "peggo_orchestrator_nonce", "legendFormat": "__auto" },
    {
     "conditions": [
      {
       "evaluator": {
        "params": [
         0,
         0
        ],
        "type": "gt"
       },
       "operator": { "type": "and" },
       "query": {
        "params": []
       },
       "reducer": {
        "params": [],
        "type": "avg"
       },
       "type": "query"
      }
     ],
     "expression": "$A - $B",
     "type": "math"
    }
   ]
  },
  {
   "title": "Network Nonce",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "peggo_network_nonce", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Orchestrator Latest Nonce",
   "type": "stat",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "peggo_network_nonce" }
   ]
  },
  {
   "title": "Nonce History",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "targets": [
    { "expr": "peggo_network_nonce", "legendFormat": "__auto" },
    { "expr": "peggo_orchestrator_nonce", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Orchestrator Balance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "targets": [
    { "expr": "peggo_orchestrator_balance", "legendFormat": "__auto" }
   ]
  }
 ]
}