{
 "title": "Stakewise V3 Operator",
 "description": "StakeWise V3 Operator",
 "tags": [
  "stakewise",
  "v3-operator"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "operator",
    "query": {
     "query": "label_values(wallet_balance,job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Operator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Block Number",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "block_number{job=~\"$operator\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outdated Signatures",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "outdated_signatures{job=~\"$operator\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Available Keys for Registration",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "unused_validator_keys{job=~\"$operator\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Balance (in ETH)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wallet_balance{job=~\"$operator\"} / 1e18",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Slot Number",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "slot_number{job=~\"$operator\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stakeable Assets (in ETH)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "stakeable_assets{job=~\"$operator\"} / 1e18",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}